name: go_eat_e_commerce_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_size_text: 3.0.0
  cached_network_image: 3.3.1
  collection: 1.18.0
  flutter_animate: 4.5.0
  flutter_cache_manager: 3.3.1
  flutter_rating_bar: 4.0.1
  flutter_svg: 2.0.9
  font_awesome_flutter: 10.7.0
  from_css_color: 2.0.0
  dropdown_button2: 2.3.9
  go_router: 12.1.3
  google_fonts: 6.1.0
  intl: 0.19.0
  json_path: 0.7.2
  page_transition: 2.1.0
  path_provider: 2.1.3
  path_provider_android: 2.2.5
  path_provider_foundation: 2.4.0
  path_provider_platform_interface: 2.1.2
  provider: 6.1.2
  shared_preferences: 2.2.2
  shared_preferences_android: 2.2.1
  shared_preferences_foundation: 2.3.4
  shared_preferences_platform_interface: 2.3.1
  shared_preferences_web: 2.2.1
  smooth_page_indicator: 1.1.0
  sqflite: 2.2.6
  styled_divider: 1.0.4
  timeago: 3.6.1
  url_launcher: 6.3.0
  url_launcher_android: 6.3.4
  url_launcher_ios: 6.3.1
  url_launcher_platform_interface: 2.3.2
  dotted_line: ^3.2.3
  permission_handler: ^11.3.1
  google_api_headers: ^1.5.0
  flutter_google_places_hoc081098: ^1.2.0
  google_maps_webservice: ^0.0.20-nullsafety.2
  google_maps: ^8.0.0
  google_maps_flutter: ^2.9.0
  google_maps_flutter_ios: ^2.13.0
#  flutter_stripe: ^11.0.0
  firebase_database: ^10.5.7
  geocoding: ^2.0.4
  geolocator: ^9.0.2
  firebase_messaging: ^14.6.2
  flutter_local_notifications: ^17.0.1
  firebase_app_check: ^0.2.1+8
  cloud_firestore: ^4.8.0
#  sign_in_with_apple: 4.3.0
#  sign_in_with_apple_platform_interface: 1.0.0
#  sign_in_with_apple_web: 1.0.1
  firebase_auth: ^4.4.1
  google_sign_in: 6.1.5
  google_sign_in_android: 6.1.20
  google_sign_in_ios: 5.6.4
  google_sign_in_platform_interface: 2.4.2
  dio: ^5.8.0+1
  intl_phone_field: ^3.1.0
  pinput: ^3.0.1
  lottie: ^2.6.0
  file_picker: ^8.0.0+1
  image_picker: ^0.8.5+3
  device_info_plus: ^9.0.0
  google_places_flutter: ^2.0.9
  connectivity_plus: ^5.0.2
  fluttertoast: ^8.2.8
  flutter_spinkit: ^5.2.1
  fl_chart: 0.68.0
  percent_indicator: ^4.2.4
  dotted_border: ^2.1.0
  firebase_core: ^3.0.0
  country_picker: ^2.0.27
  table_calendar: ^3.0.9





  #google_maps_flutter_android: ^2.14.10

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dependency_overrides:
  http: 1.2.1
  uuid: ^4.0.0
  firebase_core: ^3.0.0

dev_dependencies:
  flutter_lints: 4.0.0
  lints: 4.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/jsons/

  fonts:
    - family: 'Gilroy'
      fonts:
#        - asset: assets/fonts/Gilroy-Light.ttf
          #weight: 300
        - asset: assets/fonts/Gilroy-Regular.ttf
        - asset: assets/fonts/Gilroy-Medium.ttf
       #   weight: 500
        - asset: assets/fonts/Gilroy-Bold.ttf
        #  weight: 700
        - asset: assets/fonts/Gilroy-Heavy.ttf
        #  weight: 800


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

